version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m     
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn clean
      - run: mvn test -s settings.xml      
      - run: mvn install -s settings.xml
      - run: mvn package -s settings.xml
      - run:  (a bash command case to select environment depending on the branch where you pushed your commits)
          case $CIRCLE_BRANCH in
            'main') export environment='Sandbox';;
            'dev') export environment='Design';;
          esac;
          echo $environment; 
      - run: mvn deploy -DmuleDeploy -s settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}