version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m     
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn clean
      - run: mvn test -s settings.xml      
      - run: mvn install -s settings.xml
      - run: mvn package -s settings.xml
      - run: case $CIRCLE_BRANCH in
            'main') export environment='Sandbox';;
            'dev') export environment='Test';;
            esac;
            echo $environment; 
            mvn deploy -Denvironment=$environment -DmuleDeploy -s settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
